places = ['Mykonos', 'Istanbul', 'Split', 'Budapest', 'Tokyo']
print('original list')
print(places)
print('sorted list')
print(sorted(places))
print('list')
print(places)
print('reverese list')
places.reverse()
print(places)
print('reverse reversion list')
places.reverse()
print(places)
print('sort list')
places.sort()
print(places)
print('sort list (reverse)')
places.sort(reverse=True)
print(places)

